### ISSUE TITLE
JavaScript numbers get ceil'd

### ISSUE THREAD

**Issue by ajgreenb** [d3/d3-scale#8] opened 2015-10-09 18:50 UTC
I'm trying to create a scaled X-Axis with some large values in the domain:

```js
var xscale = d3.scale.linear()
                      .domain(d3.extent(my_data, function(d) { 
                                                           console.log("my_val " + d.my_val); 
                                                           return d.my_val })
                                    )
                     .range([0, width]);
```

The above code produces the following output, which is correct:

```
my_val 34200007505 
my_val 34200007507
my_val 34200007601
my_val 34200007875
my_val 34200008702
```

Here is the code that I use to render a chart:

```js
 var fmtVal = function(d) {
                        console.log("!!! fmt_val ===> " + d);
 }
var xaxis = d3.svg.axis().scale(xscale).orient("bottom").ticks(10).tickFormat(fmtVal);
var focus = svg.append ("g")
                        .attr("class", "focus")
                        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
focus.append("g")
                .attr("class", "x axis")
                .attr("transform", "translate(0," + height + ")")
                .call(xaxis);
```

The output from my logging statements produces:

```
!!! fmt_val ===> 34200100000
!!! fmt_val ===> 34200200000
!!! fmt_val ===> 34200300000
!!! fmt_val ===> 34200400000
```

As you can see, 34200007505 is rounded up to 34200100000. How do I prevent this from occurring?

**Comment by mbostock** [comment] 2015-10-09 19:46
Duplicate of mbostock/d3#2570, which I will now answer.

**Closed by mbostock** 2015-10-09 19:46 UTC

**Comment by ajgreenb** [comment] 2015-10-09 20:07
Thanks @mbostock! My colleague and I weren't sure where best to post our question. Perhaps StackOverflow would've been the most apt.
