### ISSUE TITLE
Time Scale: How could one provide a custom irregular spacing of ticks?

### ISSUE THREAD

**Issue by DerGuteWolf** [d3/d3-scale#262] opened 2022-05-12 10:51 UTC
As weekends are less interesting in one of our use cases, we are looking for a way to a have a time scale (and axis) in which the weekend hours are spaced more densly then the workday hours. How could the be achieved? Since there is alreay support for "irregular spacing of ticks because time intervals have varying length" this should somehow be possible, or?

**Comment by Fil** [comment] 2022-05-12 14:10
This [candlestick chart](https://observablehq.com/@d3/candlestick-chart) follows a similar requirement, by removing the week-ends. However note that it's an ordinal chart (day by day), not continuous time.

If you want to make time continuous but non-linear you can certainly write your own function from the time domain to floats, and then put back the correct ticks on the axis. I'm doing that (although with a different time warper) in this [renko chart](https://observablehq.com/@fil/renko-chart) notebook.

I'm closing the issue since this is not a bug or a thing we'd want to develop inside of d3-scale, but happy to continue the discussion.

**Closed by Fil** 2022-05-12 14:10 UTC
