### ISSUE TITLE
Quantize scale docs points to an example block for threshold scale

### ISSUE THREAD

**Issue by kanitw** [d3/d3-scale#147] opened 2018-07-23 20:17 UTC
> Each range value y can be expressed as a quantized linear function of the domain value x: y = m round(x) + b. See bl.ocks.org/4060606 for an example.

but bl.ocks.org/4060606 uses threshold, not quantize.

**Comment by mbostock** [comment] 2019-01-26 19:47
Duplicate of #94.

**Closed by mbostock** 2019-01-26 19:47 UTC
