### ISSUE TITLE
piecewise scale should be redesigned (and isn't well-enough documented)

### ISSUE THREAD

**Issue by eflister** [d3/d3-scale#227] opened 2020-10-29 17:20 UTC
i'm coming all the way from vega-lite, so i might be missing d3-specific information, happy to be enlightened.  i don't know enough to know whether only vega-lite and vega should change, or if d3-scale should as well.

i'm using a piecewise `symlog` `scale` in vega-lite to represent a field as a `y`-value in a `line` graph and a `color` on a choropleth.  i want to use the same scale for both.  the purpose of the piecewise is to reduce the dynamic range allocated to some unimportant negative values.

there's no doc on how to use piecewise in vega/vega-lite, other than specifying that `domain` and `range` should have matching numbers of elements (if one makes it all the way to https://github.com/d3/d3-scale#continuous_domain, we also learn that `domain` should be monotonic).  based on how `scale`s work, i expected the units to be arbitrary, serving only to express relative proportions.  i expected the encoding to automatically adapt to the range of outputs automatically, as usual.

but it turns out that the output `range` is interpreted directly as concrete units in the encoding, so the user has to know specifics, such as the pixel locations of the top+bottom of a graph, or the particulars of how colors are indexed.  moreover, y-values are negative-going compared to the data domain, whereas colors are not!

instead, piecewise transforms should precede the nonlinear transform and similarly use arbitrary units.

data domain
-> piecewise range (expresses relative proportions in abstract units)
-> nonlinear (symlog, etc -- input to this layer automatically matched to range of outputs of previous layer, user only cares about shape, not units)
-> concrete presentation (pixels, colors, user doesn't know or care about units cuz again the input to this layer is automatically matched to output of previous)

original report here: https://github.com/vega/vega-lite/issues/7013

i also filed this on vega: https://github.com/vega/vega/issues/2954

**Comment by mbostock** [comment] 2020-10-29 17:31
> instead, piecewise transforms should precede the nonlinear transform and similarly use arbitrary units.

Sounds like the sort of thing that needs to fixed at the Vega layer, so closing as duplicate of vega/vega#2954. I don’t understand concretely how you’d like d3.scaleSymlog or the like to behave differently, but I’m happy to reconsider if you want to clarify your desire.

**Closed by mbostock** 2020-10-29 17:31 UTC
